### ISSUE TITLE
The policy for AWS VPC CNI doesn't work out-of-the-box

### ISSUE THREAD

**Issue by dex4er** [clowdhaus/terraform-aws-eks-pod-identity#1]
The policy for AWS VPC CNI has

```
      condition {
        test     = "StringEquals"
        variable = "aws:ResourceTag/eks-cluster-arn"
        values   = ["$${aws:PrincipalTag/eks-cluster-arn}"]
      }
```

but there is no clear example how to use it: ie. do I need to add this extra tag to some resources (node group?) or with ADDITIONAL_ENI_TAGS variable for vpc-cni addon.

With this policy IAM rejects CreateNetworkInterface and AttachNetworkInterface requests.

**Comment by bryantbiggs** [comment]
Users do not need to do anything for these tags, they are embedded into the API calls. The VPC CNI currently does not support pod identity which is why its failing for you

**Comment by dex4er** [comment]
It is not true: with `amazon-k8s-cni:v1.15.5-eksbuild.1` and 

```tf
  additional_policy_arns = {
    AmazonEKS_CNI_Policy = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  }
```

everything is fine. I might guess this tag will be introduced in 1.16.0? Still fine, but maybe it should be written as requirement for this Terraform module.

**Comment by dex4er** [comment]
v1.16.0 fails with the standard policy (`attach_aws_vpc_cni_policy = true`, `aws_vpc_cni_enable_ipv4 = true`) too. All is fine when I use `arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy`.

Do I miss `ADDITIONAL_ENI_TAGS`? The documentation says VPC CNI adds `cluster.k8s.amazonaws.com/name` tag to the resources rather than `eks-cluster-arn`?

**Comment by bryantbiggs** [comment]
the session tag based policies have been removed - when the upstream projects update their policies to support, we can re-evaluate adding them here
